name=input("Enter your name: ")
age=input("Enter your age: ")
lab=input("Enter your lab number: ")
product_count=input("Enter your product count: ")
product_price=input("enter your product price: ")
print(f"your name is {name} and your age is {age} and your lab number is {lab} and your product count is {product_count} and your product price is {product_price} total price is {int(product_count) * int(product_price)}")
print(type(name),type(age))
print(type(int(age)),name)
first_number, last_number=map(int,input("enter first number and last number: ").split()[:2])
print(f"First Number: {first_number}, Last Number: {last_number}",sep="-")
a,b=input("enter a and b: ").split()
a=int(a)
b=int(b)
print(type(a and b))
print("good" , end=" ")
print("morning" , end=" ")
print("everyone!!")
a=input("total:(5 +5)")
print(a)